logging:
  level: "INFO"
  format: "%(message)s"

schema:
  allow_list_path: "allow_list.json"

retriever:
  max_chunks: 5

guardrails:
  neo4j_timeout: 10
  max_cypher_results: 25
  max_traversal_depth: 2

observability:
  metrics_enabled: true
  metrics_port: 8000

llm:
  provider: "gemini"
  model: "gemini-2.0-flash-exp"
  embedding_model: "models/text-embedding-004"
  max_tokens: 512
  rate_limit_per_minute: 60
  redis_url: "redis://localhost:6379/0"
